server:
  port: 8080
  servlet:
    context-path: /springbootMybatis
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mytestdb?useSSL=false&userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.lzp.pojo
  mapper-locations: classpath:com.lzp.mapper/*.xml