server:
  port: 8080
#  servlet:
#    context-path: /springbootAnno
spring:
  #静态资源前缀
  #  mvc:
  #    static-path-pattern: /res/**
  #指定静态资源路径
  #  web:
  #    resources:
  #      static-locations: [classpath:/myRes/]
  main:
    #解决依赖循环的问题
    allow-circular-references: true
  #    datasource:
  #    username: root
  #    password: 123456
  #    url: jdbc:mysql://127.0.0.1:3306/mytestdb?useSSL=false&userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mytestdb?useSSL=false&userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  druid:
    #初始化大小
    initialSize: 5
    #最小值
    minIdle: 5
    #最大值
    maxActive: 20
    #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
    maxWait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
    #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
    filters: stat,wall,slf4j
    #最大PSCache连接
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=500
    # 配置StatFilter
    web-stat-filter:
      #默认为false，设置为true启动
      enabled: true
      url-pattern: "/*"
      exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
    #配置StatViewServlet
    stat-view-servlet:
      url-pattern: "/druid/*"
      #允许那些ip
      allow: 127.0.0.1,localhost
      login-username: admin
      login-password: 123456
      #禁止那些ip ip黑名单 （和allow存在相同的ip时，deny优先与allow）
      deny:
      #是否可以重置 启用页面的Reset All功能
      reset-enable: false
      #启用
      enabled: true

mybatis:
  type-aliases-package: com.lzp.pojo
  mapper-locations: classpath:mybatis/*.xml  #如果mapper映射文件名和上面的文件夹命名不一样需要指定文件位置，同时需要扫描部文件


