spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytestdb
    username: root
    password: 123456
  redis:
    cluster:
      nodes:
        - 192.168.245.129:7001
        - 192.168.245.129:7002
        - 192.168.245.129:7003
        - 192.168.245.129:7004
        - 192.168.245.129:7005
        - 192.168.245.129:7006
mybatis:
  type-aliases-package: com.lzp.pojo
  mapper-locations: classpath:com/lzp/mapper/*.yml
server:
  port: 8080


