server:
  port: 8080
  servlet:
    context-path: /springbootIntegration
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/mytestdb?useSSL=false&userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.lzp.pojo
  mapper-locations: classpath:mybatis/*.xml  #如果mapper映射文件名和上面的文件夹命名不一样需要指定文件位置，同时需要扫描部文件


